language: generic
sudo: required
services:
- docker
git:
  clone: true
before_install:
        #- git clone --branch=$TRAVIS_PULL_REQUEST_BRANCH https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git $TRAVIS_PULL_REQUEST_SLUG
- echo $TRAVIS_PULL_REQUEST_SLUG
- ssh-keyscan $TEST_IP >> $HOME/.ssh/known_hosts
install:
- pwd
- ls -alrt
- openssl aes-256-cbc -K $encrypted_12f1486e37a0_key -iv $encrypted_12f1486e37a0_iv
  -in ./id_rsa.enc -out ~/.ssh/id_rsa -d
- bash ./autocheck.sh queue $TEST_IP
script:
- ssh -i skey cland@$TEST_IP "cd /opt/cloudland/ && sudo bash ./autocheck.sh pull_request
  $TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_SLUG"
- bash ./autocheck.sh test $TEST_IP
