language: generic
sudo: required
services:
- docker
git:
  clone: true
before_install:
        #- openssl aes-256-cbc -K $encrypted_7adbb8266323_key -iv $encrypted_7adbb8266323_iv
        #-in skey.enc -out ~\/skey -d
- echo $TRAVIS_PULL_REQUEST_SLUG
- ssh-keyscan $TEST_IP >> $HOME/.ssh/known_hosts
install:
- pwd
- ls -alrt
- ls -alrt ~/.ssh
- cat ~/.ssh/known_hosts
- cat ~/.ssh/authorized_keys
- cat ~/.ssh/config
- ls -alrt ~
- openssl aes-256-cbc -K $encrypted_12f1486e37a0_key -iv $encrypted_12f1486e37a0_iv
  -in ./id_rsa.enc -out ~/skey -d
  #- openssl aes-256-cbc -K $encrypted_7adbb8266323_key -iv $encrypted_7adbb8266323_iv
  #-in skey.enc -out ~/skey -d
- ls -alrt ~/.ssh
- bash ./autocheck.sh queue $TEST_IP
script:
- ssh -i skey cland@$TEST_IP "cd /opt/cloudland/ && sudo bash ./autocheck.sh pull_request
  $TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_SLUG"
- bash ./autocheck.sh test $TEST_IP
